import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        @Autowired
        ItemRepository itemRepository;
        HashMap<Integer,Item> items = new HashMap<>();
        //TODO: write code here
        for (String order : inputs) {
            String stringArray[] = order.trim().split("x");
            String id = stringArray[0];
            int count = Integer.parseInt(stringArray[1]);
            Item item = itemRepository.find(id);
            items.put(count,item);
        }
        double sum = 0;



        System.out.println("============= Order details =============");
        for (Map.Entry<Integer, Item> item : items.entrySet()) {
            double price = item.getValue().getPrice()*item.getKey();
            sum+=price;
            System.out.println(item.getValue().getName()+"x"+item.getKey()+"="+price+"yuan");
        }
        System.out.println("------------------------------------------");
        if (sum>=30){
            System.out.println("Promotion used:");
            System.out.println("Deduct 6 yuan when the order reaches 30 yuan, saving 6 yuan");
            System.out.println("------------------------------------------");
            System.out.println("In total:"+(sum-6));
            System.out.println("==========================================");
        }
        else {
            System.out.println("In total:"+(sum));
            System.out.println("==========================================");

        }



        return null;
    }

}
